version: '3.7'

services:
  mysql:
    image: mysql
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./sql:/sql"
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
